// Example: Reporter Usage
//
// Demonstrates the Reporter analytics product using the Lerian SDK v3.
// The example lists available data sources, creates a report in CSV
// format, polls for completion, and downloads the generated file.
//
// Configure via environment variables:
//
//	LERIAN_REPORTER_URL       (default: http://localhost:3004/v1)
//	LERIAN_REPORTER_AUTH_TOKEN (optional)
//	LERIAN_REPORTER_ORG_ID    (required -- the organization scope)
//	LERIAN_DEBUG              (optional, set "true" for verbose logging)
package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os"

	lerian "github.com/LerianStudio/lerian-sdk-golang"
	"github.com/LerianStudio/lerian-sdk-golang/reporter"
)

func main() {
	// -----------------------------------------------------------------------
	// Step 1: Create the SDK client configured for the Reporter product.
	//
	// Reporter requires an OrganizationID which is sent as the
	// X-Organization-Id header on every request. This scopes all report
	// operations to a single organization. Authentication uses bearer tokens.
	// -----------------------------------------------------------------------
	orgID := envOr("LERIAN_REPORTER_ORG_ID", "org-placeholder-id")

	// NOTE: Use HTTPS URLs in production. HTTP is only for local development.
	client, err := lerian.New(
		lerian.WithReporter(
			reporter.WithBaseURL(envOr("LERIAN_REPORTER_URL", "http://localhost:3004/v1")),
			reporter.WithAuthToken(os.Getenv("LERIAN_REPORTER_AUTH_TOKEN")),
			reporter.WithOrganizationID(orgID),
		),
		lerian.WithDebug(os.Getenv("LERIAN_DEBUG") == "true"),
	)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	defer client.Shutdown(context.Background())

	ctx := context.Background()

	// -----------------------------------------------------------------------
	// Step 2: List available data sources.
	//
	// Data sources represent upstream systems (databases, APIs, file feeds)
	// from which reports pull data. The DataSources service is read-only
	// since sources are typically provisioned by the platform operator.
	// -----------------------------------------------------------------------
	fmt.Println("--- Available Data Sources ---")

	dsIter := client.Reporter.DataSources.List(ctx, nil)
	var firstDataSourceID string

	for dsIter.Next(ctx) {
		ds := dsIter.Item()
		if firstDataSourceID == "" {
			firstDataSourceID = ds.ID
		}

		fmt.Printf("  - %s (type: %s, status: %s, ID: %s)\n",
			ds.Name, ds.Type, ds.Status, ds.ID)
	}

	if err := dsIter.Err(); err != nil {
		log.Fatalf("Failed to list data sources: %v", err)
	}

	// -----------------------------------------------------------------------
	// Step 3: Create a report.
	//
	// Reports are generated by specifying a name, format (pdf, csv, xlsx),
	// and optional parameters that filter or configure the report output.
	// If a data source is available we link it; otherwise the report
	// uses default data sources configured in the Reporter backend.
	// -----------------------------------------------------------------------
	reportDesc := "Monthly transaction summary for reconciliation review"

	createInput := &reporter.CreateReportInput{
		Name:        "Monthly Transaction Report",
		Description: &reportDesc,
		Format:      "csv",
		Parameters: map[string]any{
			"period":    "2026-02",
			"assetCode": "BRL",
		},
	}

	// Link to the first available data source if one was found.
	if firstDataSourceID != "" {
		createInput.DataSourceID = &firstDataSourceID
	}

	report, err := client.Reporter.Reports.Create(ctx, createInput)
	if err != nil {
		log.Fatalf("Failed to create report: %v", err)
	}

	fmt.Printf("\nCreated report: %s (ID: %s, status: %s, format: %s)\n",
		report.Name, report.ID, report.Status, report.Format)

	// -----------------------------------------------------------------------
	// Step 4: Retrieve the report to check its status.
	//
	// Report generation may be asynchronous. In a production scenario you
	// would poll until Status transitions to "completed". Here we fetch
	// once to illustrate the Get pattern.
	// -----------------------------------------------------------------------
	report, err = client.Reporter.Reports.Get(ctx, report.ID)
	if err != nil {
		log.Fatalf("Failed to get report: %v", err)
	}

	fmt.Printf("Report status: %s\n", report.Status)

	if report.GeneratedAt != nil {
		fmt.Printf("Generated at: %s\n", report.GeneratedAt.Format("2006-01-02 15:04:05"))
	}

	if report.FileSize != nil {
		fmt.Printf("File size: %d bytes\n", *report.FileSize)
	}

	// -----------------------------------------------------------------------
	// Step 5: Download the report file.
	//
	// The Download method returns the raw byte content of the generated
	// report file. The format matches what was specified during creation
	// (csv in this case). The caller decides how to persist or stream it.
	// -----------------------------------------------------------------------
	data, err := client.Reporter.Reports.Download(ctx, report.ID)
	if err != nil {
		// The report may not be ready yet; this is expected for async generation.
		fmt.Printf("Download not available yet: %v\n", err)
	} else {
		fmt.Printf("\nDownloaded report: %d bytes\n", len(data))

		// In a real application you would write to a file:
		//   os.WriteFile("report.csv", data, 0644)
		// Here we just show a preview of the first 200 bytes.
		preview := string(data)
		if len(preview) > 200 {
			preview = preview[:200] + "..."
		}

		fmt.Printf("Preview:\n%s\n", preview)
	}

	// -----------------------------------------------------------------------
	// Step 6: List all reports with pagination.
	// -----------------------------------------------------------------------
	fmt.Println("\n--- All Reports ---")

	reportIter := client.Reporter.Reports.List(ctx, nil)
	for reportIter.Next(ctx) {
		r := reportIter.Item()
		fmt.Printf("  - %s (format: %s, status: %s)\n", r.Name, r.Format, r.Status)
	}

	if err := reportIter.Err(); err != nil {
		log.Fatalf("Failed to list reports: %v", err)
	}

	// -----------------------------------------------------------------------
	// Step 7: Error handling -- demonstrate ErrNotFound.
	// -----------------------------------------------------------------------
	_, err = client.Reporter.Reports.Get(ctx, "non-existent-report-id")
	if err != nil {
		if errors.Is(err, lerian.ErrNotFound) {
			fmt.Println("\nCorrectly caught ErrNotFound for non-existent report")
		} else {
			fmt.Printf("\nUnexpected error: %v\n", err)
		}
	}

	fmt.Println("\nReporter usage workflow complete!")
}

// envOr returns the value of the environment variable named by key, or
// the fallback value if the variable is empty or unset.
func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}

	return fallback
}
